### ISSUE TITLE
dB Value issue

### ISSUE THREAD

**Issue by oleamundsen** [bitfocus/companion-module-bss-soundweb#11] opened 2024-08-07 12:04 UTC
Hi!

Happy with the module. Have just encountered one problem I can't resolve.

I have set the full parameter value which controls gain in channel 3 of an Automixer in Audio Architect.
When I try to control the gain fader it refuses to go below 0.00dB. Same with the feedback.
Above 0.00dB all works fine.

Is there something Im missing?

**Comment by oleamundsen** [comment] 2024-08-09 12:02
Hi again.

After some troubleshooting it seems this issue is only present when converting tcp to rs232.
We have an old "atop se5002" which allow us to use then com-port in our blu-160.
When reading the HARMAN blu-160 manual it states that ethernet and rs232 should behave the same.

Could it be the se5002 converter? Or some settings I've missed?

**Comment by AndyFug** [comment] 2024-08-23 07:06
Hi.  Apologies I have only just seen this.  I have been away on holidays etc.  Is this still an issue?

Unfortunately this may be hard for me to reproduce because I don't think I have a serial adaptor.  It would be great if you can reproduce it over TCP. 

It does sound a little odd.  Can you send screenshots of your settings in Companion?

**Comment by oleamundsen** [comment] 2024-08-28 12:01
<img width="2006" alt="Skjermbilde 2024-08-28 kl  13 52 14" src="https://github.com/user-attachments/assets/476288fb-f9f2-48eb-b630-6354f8b2aa8a">
<img width="2003" alt="Skjermbilde 2024-08-28 kl  13 53 00" src="https://github.com/user-attachments/assets/85e04f6c-5392-45e6-b89c-18bfa595c7be">
<img width="2004" alt="Skjermbilde 2024-08-28 kl  13 55 38" src="https://github.com/user-attachments/assets/025a9481-07f8-479f-8733-c28edaf058ce">

No worries. The issue persists. I'm almost certain that the serial adapter is the problem - although I do not know why.
Just tried it on a blu-80 in a test-lab and it refuses to go below 0dB.
When using the module over TCP it works fine. Even tried sending HEX with the generic TCP/UDP module and it works fine too..
I'm baffled..

**Comment by AndyFug** [comment] 2024-08-28 14:19
Thanks for the feedback.

Few questions:
1. So when you send hex with the generic TCP/UDP module via your serial adaptor it works fine and can set the value below 0dB?
2. Is it the same behaviour when setting the value with an 'absolute' rather than 'relative' value.  Ie. Can you set an absolute value of -1dB?
3. Is it the same behaviour when setting with percent and raw units?
4. Is it the same behaviour when using a normal Gain object and using the "Gain N-Input:Gain" action?

So I can dig into this a bit more, can you open the module logging page with debug messages enabled and send across the logs under two scenarios:

1. When trying to set below 0dB via the serial adaptor
2. When trying to set below 0dB directly via TCP. 

Make sure you are using exactly the same action config  etc and same context/starting position on the fader.

**Comment by oleamundsen** [comment] 2024-09-02 11:52
<img width="1120" alt="VIA_ETHERNET_-dB_blu-80" src="https://github.com/user-attachments/assets/b8d04193-4f08-4878-a4da-35f5962e2075">
<img width="1518" alt="VIA_SERIAL_-dB_blu-160" src="https://github.com/user-attachments/assets/0a1f6f0e-a25b-4329-aef3-f88c26503070">
<img width="1517" alt="VIA_SERIAL_+dB_blu-160" src="https://github.com/user-attachments/assets/25cf95e9-05f1-446c-9c58-a4fcb4236e2c">

I only used the BSS-module in companion in the pictures above. Due to network constrictions I didn't have time to test with HEX today.

**Comment by AndyFug** [comment] 2024-09-23 07:52
Apologies for the slow response... It's been a busy couple of weeks.  Thanks for the screen grabs.

So this definitely suggests that it is something to do with the serial adaptor.  (Assuming everything else is the same... the type of object you are controlling, the serial settings on the BLU-80 and BLU-160 etc).

It appears to be a function of trying to set a negative number, which suggests it may be a hex value that your serial adaptor is replacing when it sees it.  Negative numbers are represented using twos complement, which, from memory, I think will result in quite a few 0xFF values.  Like I mentioned before, it would be interesting to review your settings on the serial adaptor (SE50002).

Based on the evidence above (Particularly that negative values sent using the generic TCP/UDP module via this particular serial adaptor also exhibit the same symptoms), I think we should close this as an issue with the Soundweb Companion module.  Would you agree?

Happy to continue the discussion because it may be helpful to others if we find a solution.

**Comment by oleamundsen** [comment] 2024-09-23 12:16
No problem. And thanks for clearing things up. 
Close the issue as I feel we got a solid conclusion.

Tanks again!

**Closed** 2024-09-23 16:05 UTC

**Comment by AndyFug** [comment] 2024-12-04 18:33
@oleamundsen Random question out of the blue I know... How did you format those buttons in the screen grabs above where half the button is purple and the other half is black?  Is it just a PNG background?

**Comment by oleamundsen** [comment] 2024-12-04 18:38
Its a custom made .png.
